name: Validate filenames

on:
  push:
    branches:
     - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate filenames
        run: |
          find . -name "*" -type f -print | grep -vE '^((?![\\\/:*?\"<>|]).)*$' && echo "All filenames valid" || (echo "Found invalid filenames!" && exit 1)
