name: Validate filenames

on:
  push:
    branches:
     - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Validate File/Folder names
        run: |
          ruby ./check_basenames.rb
